### ISSUE TITLE
Implement Array.reduce solution has incorrect call back invocation

### ISSUE THREAD

**Issue by flashyrc** [nitish24p/js-vault#14]
Shouldn't the below be callback.call(accumulator, this[index], index, this) instead of callback.call(**accumulator**, **accumulator**, this[index], index, this)?

![image](https://user-images.githubusercontent.com/6216427/58500872-b997e200-81a0-11e9-9ce8-6b6a27675bd3.png)

**Comment by nitish24p** [comment]
The `call` method is of the following form 
> function.call(thisArg, arg1, arg2, ...)

The first argument is the context, and the next arguments are an optional coma separated values of the params passed to the function

hence in this case the context is `accumulator` as this can be the starting value or any value for that reason, the next argument i.e `accumulator, this[index]` are actually the parameters to the reduce function.

**Comment by flashyrc** [comment]
I am not sure how I missed the "call" there. I think I just looked at my trial (direct function call) and jumped the gun. Only thing in my favour is this is my first ever reported issue in github.  Ha ha. Closing.
